### ISSUE TITLE
OS Error occured when save model pth file using 8GPU

### ISSUE THREAD

**Issue by tanmodong** [ShoufaChen/DiffusionDet#39]
Hello.

Thanks for excellent detection algorighm.

I faced OSError when saving the model when using 8 GPU training.

Is that a problem of my environment or known error?

[12/20 18:16:09 d2.utils.events]:  eta: 19:46:55  iter: 4959  total_loss: 10.31  loss_ce: 0.8514  loss_bbox: 0.3865  loss_giou: 0.4012  loss_ce_0: 0.902  loss_bbox_0: 0.4758  loss_giou_0: 0.4936  loss_ce_1: 0.8713  loss_bbox_1: 0.4325  loss_giou_1: 0.4167  loss_ce_2: 0.8526  loss_bbox_2: 0.4106  loss_giou_2: 0.4151  loss_ce_3: 0.8237  loss_bbox_3: 0.409  loss_giou_3: 0.391  loss_ce_4: 0.8287  loss_bbox_4: 0.4046  loss_giou_4: 0.4085  time: 0.2815  data_time: 0.0115  lr: 2.5e-05  max_mem: 5418M
[12/20 18:16:14 d2.utils.events]:  eta: 19:46:57  iter: 4979  total_loss: 9.924  loss_ce: 0.7974  loss_bbox: 0.3912  loss_giou: 0.3875  loss_ce_0: 0.8377  loss_bbox_0: 0.4803  loss_giou_0: 0.448  loss_ce_1: 0.8489  loss_bbox_1: 0.3942  loss_giou_1: 0.3934  loss_ce_2: 0.8181  loss_bbox_2: 0.4009  loss_giou_2: 0.3799  loss_ce_3: 0.7867  loss_bbox_3: 0.3836  loss_giou_3: 0.38  loss_ce_4: 0.7726  loss_bbox_4: 0.3905  loss_giou_4: 0.3784  time: 0.2814  data_time: 0.0108  lr: 2.5e-05  max_mem: 5418M
[12/20 18:16:20 fvcore.common.checkpoint]: Saving checkpoint to ./output/model_0004999.pth
ERROR [12/20 18:16:20 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/acd14181ss/difdet/lib/python3.8/site-packages/torch/serialization.py", line 423, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/acd14181ss/difdet/lib/python3.8/site-packages/torch/serialization.py", line 650, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
OSError: [Errno 7] Argument list too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acd14181ss/difdet/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 128, in save
    torch.save(data, f)
  File "/home/acd14181ss/difdet/lib/python3.8/site-packages/torch/serialization.py", line 424, in save
    return
  File "/home/acd14181ss/difdet/lib/python3.8/site-packages/torch/serialization.py", line 299, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:325] . unexpected pos 361728768 vs 361728656

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acd14181ss/difdet/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 150, in train
    self.after_step()
  File "/home/acd14181ss/difdet/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 180, in after_step
    h.after_step()
  File "/home/acd14181ss/difdet/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 206, in after_step
    self.step(self.trainer.iter)
  File "/home/acd14181ss/difdet/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 430, in step
    self.checkpointer.save(
  File "/home/acd14181ss/difdet/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 128, in save
    torch.save(data, f)
OSError: [Errno 7] Argument list too long
[12/20 18:16:20 d2.engine.hooks]: Overall training speed: 4997 iterations in 0:23:26 (0.2815 s / it)
[12/20 18:16:20 d2.engine.hooks]: Total training time: 0:23:38 (0:00:11 on hooks)
[12/20 18:16:20 d2.utils.events]:  eta: 19:46:44  iter: 4999  total_loss: 9.931  loss_ce: 0.8132  loss_bbox: 0.3718  loss_giou: 0.3842  loss_ce_0: 0.881  loss_bbox_0: 0.476  loss_giou_0: 0.4806  loss_ce_1: 0.859  loss_bbox_1: 0.407  loss_giou_1: 0.4112  loss_ce_2: 0.8139  loss_bbox_2: 0.3961  loss_giou_2: 0.399  loss_ce_3: 0.8251  loss_bbox_3: 0.3842  loss_giou_3: 0.3866  loss_ce_4: 0.818  loss_bbox_4: 0.3894  loss_giou_4: 0.3854  time: 0.2814  data_time: 0.0117  lr: 2.5e-05  max_mem: 5418M

**Comment by tanmodong** [comment]
sorry, solved the problem. It's just a run out of disk space.
https://discuss.pytorch.org/t/torch-save-triggers-error-when-saving-model/125790

**Comment by ShoufaChen** [comment]
Hi,

Happy to see that you have solved this problem. Closed this issue.

Feel free to open it if you have further questions.
